export const LEVELS = {
  LEVEL_1: {
    id: 'LEVEL_1',
    name: 'Starter Bot',
    number: 1,
    color: 'level-1',
    description: 'Begin your robotics journey with basic concepts',
    icon: '🤖',
  },
  LEVEL_2: {
    id: 'LEVEL_2',
    name: 'Gear Builder',
    number: 2,
    color: 'level-2',
    description: 'Learn about gears, motors, and simple mechanisms',
    icon: '⚙️',
  },
  LEVEL_3: {
    id: 'LEVEL_3',
    name: 'Robot Explorer',
    number: 3,
    color: 'level-3',
    description: 'Explore sensors and basic programming',
    icon: '🔍',
  },
  LEVEL_4: {
    id: 'LEVEL_4',
    name: 'Circuit Master',
    number: 4,
    color: 'level-4',
    description: 'Master electronics and circuit design',
    icon: '⚡',
  },
  LEVEL_5: {
    id: 'LEVEL_5',
    name: 'Atribot Pro',
    number: 5,
    color: 'level-5',
    description: 'Build advanced autonomous robots',
    icon: '🏆',
  },
} as const;

export type LevelId = keyof typeof LEVELS;

export const getLevelInfo = (levelId: LevelId) => LEVELS[levelId];

export const SAMPLE_COURSES = [
  {
    id: '1',
    title: 'Introduction to Robotics',
    slug: 'intro-robotics',
    level: 'LEVEL_1' as LevelId,
    description: 'Learn the basics of robotics and build your first robot!',
    thumbnail: '/placeholder.svg',
    lessonsCount: 8,
    duration: '2 hours',
  },
  {
    id: '2',
    title: 'Building with Motors',
    slug: 'building-motors',
    level: 'LEVEL_1' as LevelId,
    description: 'Discover how motors work and create moving projects.',
    thumbnail: '/placeholder.svg',
    lessonsCount: 6,
    duration: '1.5 hours',
  },
  {
    id: '3',
    title: 'Gears and Mechanisms',
    slug: 'gears-mechanisms',
    level: 'LEVEL_2' as LevelId,
    description: 'Explore gear ratios and mechanical advantage.',
    thumbnail: '/placeholder.svg',
    lessonsCount: 10,
    duration: '3 hours',
  },
  {
    id: '4',
    title: 'Sensor Technology',
    slug: 'sensor-tech',
    level: 'LEVEL_3' as LevelId,
    description: 'Learn about different sensors and how robots see the world.',
    thumbnail: '/placeholder.svg',
    lessonsCount: 12,
    duration: '4 hours',
  },
  {
    id: '5',
    title: 'Programming Basics',
    slug: 'programming-basics',
    level: 'LEVEL_3' as LevelId,
    description: 'Write your first robot programs using block coding.',
    thumbnail: '/placeholder.svg',
    lessonsCount: 15,
    duration: '5 hours',
  },
  {
    id: '6',
    title: 'Circuit Design',
    slug: 'circuit-design',
    level: 'LEVEL_4' as LevelId,
    description: 'Design and build your own electronic circuits.',
    thumbnail: '/placeholder.svg',
    lessonsCount: 14,
    duration: '4.5 hours',
  },
  {
    id: '7',
    title: 'Autonomous Navigation',
    slug: 'autonomous-nav',
    level: 'LEVEL_5' as LevelId,
    description: 'Build robots that can navigate on their own!',
    thumbnail: '/placeholder.svg',
    lessonsCount: 18,
    duration: '6 hours',
  },
];

export const SAMPLE_LESSONS = [
  {
    id: '1',
    courseId: '1',
    title: 'What is a Robot?',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    content: 'In this lesson, we will learn what makes something a robot...',
    order: 1,
    duration: '10 min',
  },
  {
    id: '2',
    courseId: '1',
    title: 'Parts of a Robot',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    content: 'Every robot has important parts that work together...',
    order: 2,
    duration: '15 min',
  },
  {
    id: '3',
    courseId: '1',
    title: 'Building Your First Robot',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    content: 'Now it\'s time to build! Follow these steps...',
    order: 3,
    duration: '20 min',
  },
];
